name: total-recall
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip=23.0
  - nodejs=20.0
  - pip:
    - fastapi==0.115.0
    - uvicorn==0.34.0
    - python-jose==3.3.0
    - python-multipart==0.0.6
    - requests==2.31.0
    - beautifulsoup4==4.12.2
    - websockets==11.0.3
    - pytest==7.4.0
    - pytest-asyncio==0.21.1
    - httpx==0.24.1
    - selenium==4.11.2
    - webdriver-manager==4.0.0
