global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'totalrecall'
    static_configs:
      - targets: ['api:8000']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
